name: ota_update
description: A Flutter plugin providing ota updates for Android and iOS, with download progress (Android only)
version: 5.1.0
homepage: https://github.com/4Q-s-r-o/ota_update

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.5"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: sk.fourq.otaupdate
        pluginClass: OtaUpdatePlugin
